{% set version = "0.2.0" %}

package:
  name: pymt_hydrotrend
  version: {{ version }}

source:
  url: https://github.com/mcflugen/pymt_hydrotrend/archive/v{{ version }}.tar.gz
  sha256: 7bc4ad079458012422a927eb76166b026940067cac880cab8545b4b5ccccaef7

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win and vc<14 ]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - hydrotrend 

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hydrotrend 

test:
  imports:
    - pymt_hydrotrend

about:
  home: https://github.com/mcflugen/pymt_hydrotrend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the hydrotrend BMI.
  dev_url: https://github.com/mcflugen/pymt_hydrotrend

extra:
  recipe-maintainers:
    - mcflugen
