{% set version = "0.2.2" %}

package:
  name: pymt_hydrotrend
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/pymt_hydrotrend/archive/v{{ version }}.tar.gz
  sha256: 10716ad4970d457b424415e4d976aeb464b7a3e8304acab1835a7d7d3d9aaa09

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - bmi-c
    - cython
    - numpy
    - hydrotrend 

  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - hydrotrend 

test:
  requires:
    - bmi-tester
  commands:
    - bmi-test pymt_hydrotrend:Hydrotrend -vvv

about:
  home: https://github.com/mcflugen/pymt_hydrotrend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the hydrotrend BMI.
  dev_url: https://github.com/mcflugen/pymt_hydrotrend

extra:
  recipe-maintainers:
    - mcflugen
