{% set version = "0.1.1" %}

package:
  name: pymt_hydrotrend
  version: {{ version }}

source:
  url: https://github.com/mcflugen/pymt_hydrotrend/archive/v{{ version }}.tar.gz
  sha256: f41f6aecb71cd70febafb40483ec195c40e70f7c7e3f9e35844d40f8d19ad020

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - hydrotrend 

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pymt
    - hydrotrend 

test:
  imports:
    - pymt
    - pymt_hydrotrend

about:
  home: https://github.com/mcflugen/pymt_hydrotrend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the hydrotrend BMI.
  dev_url: https://github.com/mcflugen/pymt_hydrotrend

extra:
  recipe-maintainers:
    - mcflugen
