{% set version = "0.1.2" %}

package:
  name: pymt_hydrotrend
  version: {{ version }}

source:
  url: https://github.com/mcflugen/pymt_hydrotrend/archive/v{{ version }}.tar.gz
  sha256: bb42014b2e120ddc84096a25f386a50426515ecc1e73780b6550cfb3e52fb50d

build:
  number: 1003
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - model_metadata
    - hydrotrend 

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hydrotrend 

test:
  imports:
    - pymt_hydrotrend

about:
  home: https://github.com/mcflugen/pymt_hydrotrend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the hydrotrend BMI.
  dev_url: https://github.com/mcflugen/pymt_hydrotrend

extra:
  recipe-maintainers:
    - mcflugen
