{% set version = "0.2.1" %}

package:
  name: pymt_hydrotrend
  version: {{ version }}

source:
  url: https://github.com/mcflugen/pymt_hydrotrend/archive/v{{ version }}.tar.gz
  sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win or py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - hydrotrend 

  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - hydrotrend 

test:
  requires:
    - bmi-tester
  imports:
    - bmi-test pymt_hydrotrend:Hydrotrend -vvv

about:
  home: https://github.com/mcflugen/pymt_hydrotrend
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the hydrotrend BMI.
  dev_url: https://github.com/mcflugen/pymt_hydrotrend

extra:
  recipe-maintainers:
    - mcflugen
