travis:
  secure:
    BINSTAR_TOKEN: ch6kdnm62HZmSfCY8zORwgWE0/GPLxMm9kSmQXPTTSVTLA4vYGwPbjd3rpOL7UalCodExhjBvlCCODqiFv10X15UdfwViiNlCNQvMjsTDTUQGXTc64kelbFYgG3tdlgG3K0crvB2VVidFJ8hTvghH9J/iK0Nv3kL42iH15aw/onFCtJjEJ+mpTHufUoOFnhSpgMqLcvCVt1UQivfeG6IBlIvPyDyae69d1b7TeSZkVe9ez7uVTVd+usejVsOPfTzAHDOMd8IRr7h8obxjNQ1vQnk0mG/pJcmkO2ZHR1tVT+IXSS9HmokDInlHxiJ+wN1MPxWAsrmWfwm3tc7Utfe1W8P3DT+u8zXwEyX4mKooBynSdJnI/j1ukGsr8wz768X8mhchSZu+ps0PovHYQ+vkt+F58JjfzC8zWxWySip+DXva88pVVMrKfjNK/GfbE7Y3TqjQihVng/Z2H+ciWxkHiJECnQKtRBifgH1CYhi3mslMV12rplc4gYnfoDxW+i8/HzJrYMzsH1cM/a/LcEZ0yUgKm2xHMDgqGTHr26zabkB6MsxdRNiMuAvb2kQ64TZHE4oZO1z7jnBMFZNl7OMA7XC9CNgfFgp2I+8EpW6GWd3Vaok4C3Z5aBGL8wcCouyZY+xZHx4lEgBQ/Abtd7fY6m0hhl2nuaUjBZoojPDgPc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
